# Project: VocabularyQuiz
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../bin/Windows/obj/VocabularyQuiz_private.res
OBJ      = ../bin/Windows/obj/training.o ../bin/Windows/obj/util.o ../bin/Windows/obj/VocabularyQuiz.o ../bin/Windows/obj/parser.o ../bin/Windows/obj/UI.o ../bin/Windows/obj/test2.o $(RES)
LINKOBJ  = ../bin/Windows/obj/training.o ../bin/Windows/obj/util.o ../bin/Windows/obj/VocabularyQuiz.o ../bin/Windows/obj/parser.o ../bin/Windows/obj/UI.o ../bin/Windows/obj/test2.o $(RES)
LIBS     = -L"D:/Software/System/Dev-Cpp/MinGW64/lib" -L"D:/Software/System/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Software/System/Dev-Cpp/MinGW64/include" -I"D:/Software/System/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/System/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/include"
CXXINCS  = -I"D:/Software/System/Dev-Cpp/MinGW64/include" -I"D:/Software/System/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Software/System/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/12.2.0/include"
BIN      = ../bin/Windows/VocabularyQuiz.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -fextended-identifiers
CFLAGS   = $(INCS) -std=c++11 -fextended-identifiers
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../bin/Windows/obj/training.o: ../src/training.cpp
	$(CPP) -c ../src/training.cpp -o ../bin/Windows/obj/training.o $(CXXFLAGS)

../bin/Windows/obj/util.o: ../src/util.cpp
	$(CPP) -c ../src/util.cpp -o ../bin/Windows/obj/util.o $(CXXFLAGS)

../bin/Windows/obj/VocabularyQuiz.o: ../src/VocabularyQuiz.cpp
	$(CPP) -c ../src/VocabularyQuiz.cpp -o ../bin/Windows/obj/VocabularyQuiz.o $(CXXFLAGS)

../bin/Windows/obj/parser.o: ../src/UI/parser.cpp
	$(CPP) -c ../src/UI/parser.cpp -o ../bin/Windows/obj/parser.o $(CXXFLAGS)

../bin/Windows/obj/UI.o: ../src/UI/UI.cpp
	$(CPP) -c ../src/UI/UI.cpp -o ../bin/Windows/obj/UI.o $(CXXFLAGS)

../bin/Windows/obj/test2.o: ../src/testing/test2.cpp
	$(CPP) -c ../src/testing/test2.cpp -o ../bin/Windows/obj/test2.o $(CXXFLAGS)

../bin/Windows/obj/VocabularyQuiz_private.res: VocabularyQuiz_private.rc 
	$(WINDRES) -i VocabularyQuiz_private.rc --input-format=rc -o ../bin/Windows/obj/VocabularyQuiz_private.res -O coff 

